sudo: required
services:
        - docker

before_install:
        - docker build -t sundayanirut/docker-react -f Dockerfile.dev .

script:
        - docker run sundayanirut/docker-react npm run test -- --coverage
        
before_deploy: "echo 'ready?'"
deploy:
        # provider: elasticbeanstalk
        #region: "ap-southeast-1"
        #app: "docker"
        #env: "Docker-env"
        #bucket_name: "elasticbeanstalk-ap-southeast-1-487538390303"
        #bucket_path: "docker"
        #on:
        #        branch: master
        #access_key_id: $AWS_ACCESS_KEY
        #secret_access_key: $AWS_SECRET_KEY

        provider: elasticbeanstalk
  access_key_id:
          secure: "Encrypted $AWS_ACCESS_KEY"
    secret_access_key:
          secure: "Encrypted $AWS_SECRET_KEY"
    region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-487538390303"
