sudo: required
services:
        - docker

before_install:
        - docker build -t sundayanirut/docker-react -f Dockerfile.dev .

script:
        - docker run sundayanirut/docker-react npm run test -- --coverage

